[misp]

# MISP Server Name
name = "My MISP Server"

# MISP server URL
url = "https://localhost"

# API key to access MISP server
key = "changeme"

# TLS verification
ssl = true

# Enable
enable = true